### PR TITLE
Lint, guard `Molecule` import

### LINKED ISSUE #56: Do not have top-level toolkit imports
## Expected behavior ##

There's no real need to have top-level toolkit imports and it's creating an import loop in the toolkit: https://github.com/openforcefield/openff-toolkit/pull/1700#discussion_r1310660172

It should be fairly easy to move these imports to the individual functions.

I believe the guarded `if typing.TYPE_CHECKING` should be ok for type signatures?

### PR DESCRIPTION
**Pull request by mattwthompson**
Fixes #56 

Changes made in this Pull Request:

 - Update `pre-commit` config
 - Re-run linters
 - Avoid `Molecule` import at high-level import time

```python
>>> import sys
>>> from openff.nagl import __version__
>>> len([key for key in sys.modules if key.startswith("openff.toolkit.utils")])
# upstream/main -> HEAD
12 -> 11
>>> len([key for key in sys.modules if key.startswith("openff.toolkit.topology")])
4 -> 0
```

Questions
- Since some of the wrappers here import from various `openff.toolkit.utils` classes, I'm not sure if _all_ toolkit imports can easily be guarded
- Import time on my machine is really slow - I haven't profiled this but I'm assuming it's heavy upstreams (PyTorch? DGL?)
- Open to adding the https://pre-commit.ci/ bot here? Mostly to keep the config up-to-date

PR Checklist
------------
 - [ ] Tests?
 - [ ] Docs?
 - [ ] CHANGELOG updated?
 - [ ] Issue raised/referenced?

### CODE REVIEW

**Comment by lilyminium** [comment]
Would it be possible to separate out the linting from the Molecule imports? It's a bit difficult to see what's meaningfully changed 😅

**Comment by lilyminium** [comment]
> Since some of the wrappers here import from various openff.toolkit.utils classes, I'm not sure if all toolkit imports can easily be guarded

That's a good point. The toolkitwrappers are also somewhat separate from the rest of the code though and should mostly be used in featurising -- I suspect that the vast majority of the imports of `openff.nagl.toolkits` actually import `capture_toolkit_warnings`, a non-essential utility that we could potentially upstream (it fixes https://github.com/openforcefield/openff-toolkit/issues/1655).

**Comment by lilyminium** [comment]
> Import time on my machine is really slow - I haven't profiled this but I'm assuming it's heavy upstreams (PyTorch? DGL?)

Raised #58 to look at!

**Comment by lilyminium** [comment]
> Open to adding the [pre-commit.ci](https://pre-commit.ci/) bot here? Mostly to keep the config up-to-date

Sure :)

**Comment by mattwthompson** [comment]
I think I'll probably two this in two (independent) steps

1. Lint, possibly with a few smaller PRs into a staging branch so that each can be accepted or declined more easily
2. Guard toolkit imports, including both `Molecule` and wrappers (possibly requiring https://github.com/openforcefield/openff-toolkit/pull/1705?)

**Pull request closed without merging**
