### PR TITLE
Switch to base toolkit package

### PR DESCRIPTION
**Pull request by mattwthompson**
I'm not necessarily sure this should be merged; the objective here is to see what happens in tests if NAGL is provided `openff-toolkit-base` and if anything is missing and needs to be packaged.

Changes made in this Pull Request:

 - Switch to using `openff-toolkit-base`

PR Checklist
------------
 - [x] Switch to using `openff-toolkit-base`
 - [ ] Add back any dependencies not brought in by `openff-toolkit-base`
 - [ ] Tests?
 - [ ] Docs?
 - [ ] CHANGELOG updated?
 - [ ] Issue raised/referenced?

### CODE REVIEW

**Comment by mattwthompson** [comment]
Surprisingly only people like me who don't think things through, the tests here fail because AmberTools is needed for AM1-BCC charges when `openeye=false`. I'd like to be able to hand-wave this away and argue it should remain a test-only dependency. That doesn't seem satisfactory, though, since code like

```python
MoleculeRecord.from_openff(
            offmol,
            generate_conformers=True,
            partial_charge_methods=["am1bcc"],
            bond_order_methods=["am1"],
        )
```

bubbles up with the expected `ValueError: No registered toolkits can provide the capability "assign_partial_charges" ...`. Is this viewed as an acceptable outcome? I mean, if the user doesn't have something installed that provides AM1-BCC, I don't know how they'd expect a method named `MoleculeRecord.from_openff` to work. I don't know the code well enough to asses if `MoleculeRecord` is core functionality or not. Another option here would be to catch and handle this case.

**Comment by lilyminium** [comment]
`MoleculeRecord`*was* core functionality, but will stop being so in 0.3.x (everything in `storage` is going away) and the replacement will hopefully be clearer in that you need to have a charge method available -- the replacement will be something like `openff.nagl.training._loss.ChargeReadout.compute_reference`. That being said, I think you could do `MoleculeRecord.from_openff(partial_charge_methods=[])` currently and it would still work -- so I'm happy for the user to try doing something am1 related and bump into this error if they don't have requisite toolkitwrappers enabled.

Would it be alright if I put this temporarily on hold until I push more into https://github.com/openforcefield/openff-nagl/tree/sqlite-to-pyarrow?

**Comment by mattwthompson** [comment]
Happy to pick this up whenever those changes are pushed through

**Comment by lilyminium** [comment]
Closing as superseded by #45.

**Pull request closed without merging**
