### PR TITLE
Fixes to docs and an example

### PR DESCRIPTION
**Pull request by Yoshanuikabundi**
I found over at openff-docs that train-gnn-notebook.ipynb had broken at some point since 0.2.2. This fixes that. I think this'll let us bring the central examples up to date with nagl but I'm not sure. Then I found that the API docs were not very complete - they were failing to a bug in Sphinx 5, so I've upgraded to Sphinx 6 and MyST 1.0... which then opened a big can of worms.

Changes made in this Pull Request:

 - Add `version` argument to `train-gnn-notebook.ipynb`
 - Update Sphinx to 6.x
 - Update MyST to 1.0
 - Switch to Conda Forge DGL in examples and docs environments
 - Update autosummary templates to work with Sphinx 6
 - Fix new Intersphinx link format for MyST 1.0 (it's now `(<Link text>)[inv:<package>#<reference>]` instead of `(<Link text>)[<package>:<reference>]`)
 - Fix docstring warnings where possible (main one was that continuing lines in lists in RST must be indented to match the start of the text of the line, not the list signifier)
 
 So it's:
```rest
1. this is a very long
   sentence
2. point two
```

not

```rest
1. this is a very long
sentence
2. point two
```

Questions:

- Would you like me to set up a GitHub Action to run the examples?
- There are some MyST warnings from `theory.md` and `training.md` because the relevant parts of the API seem to have been moved - how should they be updated?

```
/home/joshmitchell/Documents/openff/nagl/docs/theory.md:91: WARNING: 'myst' cross-reference target not found: 'openff.nagl.storage.record.MoleculeRecord.from_openff' [myst.xref_missing]
/home/joshmitchell/Documents/openff/nagl/docs/theory.md:91: WARNING: 'myst' cross-reference target not found: 'openff.nagl.storage.record.MoleculeRecord.from_precomputed_openff' [myst.xref_missing]
/home/joshmitchell/Documents/openff/nagl/docs/training.md:17: WARNING: 'myst' cross-reference target not found: 'openff.nagl.storage.record.MoleculeRecord' [myst.xref_missing]
/home/joshmitchell/Documents/openff/nagl/docs/training.md:55: WARNING: 'myst' cross-reference target not found: 'openff.nagl.nn.dataset.DGLMoleculeLightningDataModule' [myst.xref_missing]
```

PR Checklist
------------
 - [ ] Tests?
 - [ ] Docs?
 - [ ] CHANGELOG updated?
 - [ ] Issue raised/referenced?

### CODE REVIEW

**Comment by lilyminium** [comment]
Amazing, thank you @Yoshanuikabundi!

> Would you like me to set up a GitHub Action to run the examples?

This would be great -- yes please!

> There are some MyST warnings from theory.md and training.md because the relevant parts of the API seem to have been moved - how should they be updated?

The ``storage`` classes don't exist anymore as I've mostly moved towards just using plain Arrow datasets instead, which were more flexible when trying to work with multiple/custom targets. Looking through `theory.md`, those references could just be removed since for training a `openff.nagl.molecule._dgl.molecule.DGLMolecule` is just constructed from an OpenFF Molecule (for inference, a networkx-enabled `openff.nagl.molecule._graph.molecule.GraphMolecule` may be constructed instead).

For the `training.md` document I have code I'd like to adapt to replace that (and generally update the documentation) -- unfortunately I don't have that exactly to hand at the moment as most of it's on the lilac cluster, which I've temporarily lost access to for the moment. The `DGLMoleculeLightningDataModule` has generally been replaced by a configuration classes, specifically `openff.nagl.config.data.DataConfig`.

**Comment by Yoshanuikabundi** [comment]
Mmm OK maybe we should leave further docs changes for a future PR then! I'll see if I can put together a quick examples runner to finish this one off.

**Comment by lilyminium** [comment]
Thanks @Yoshanuikabundi! The changes all look good to me so far, let me know when you're after an official review :-)

**Comment by lilyminium** [comment]
@Yoshanuikabundi just picking this back up again, should I keep waiting to review in case you're planning any future changes or is this good to go? :-)

**Comment by lilyminium** [comment]
I think the changes in this PR fixed #93 too, hurray! Thank you very much @Yoshanuikabundi for the great work here.

**Comment by Yoshanuikabundi** [comment]
Ah awesome! Sorry, I completely dropped this on the floor and forgot about it.

**Pull request merged**
