### PR TITLE
Pydantic v1 and v2 compatibility

### PR DESCRIPTION
**Pull request by mattwthompson**
Changes made in this Pull Request:

 - Makes codebase work on Pydantic v1 and v2
 - Adds tests for both Pydantic versions

PR Checklist
------------
 - [ ] Tests? Not explicitly
 - [ ] Docs? No, not sure it's appropriate
 - [ ] CHANGELOG updated? Not sure where exactly to do that is the `CHANGELOG.md` file in root being used for this?
 - [ ] Issue raised/referenced? No

### CODE REVIEW

**Comment by lilyminium** [comment]
Thanks @mattwthompson! Looks like any environment with Pydantic 2 is struggling to resolve... would you have any insight?

**Comment by mattwthompson** [comment]
I simply didn't notice the
```
  - pydantic <2
```
in the test environments.

This should be good to go; I'll let you decide how you want to slim down the matrix. In principle there's no need to test v1 long-term; of course it might be useful to test them both for some period of time.

**Review by lilyminium — APPROVED** [review]

**Comment by mattwthompson** [comment]
Great - testing more combinations of supported upstreams, rather than fewer, is my preference anyway.

**Comment by mattwthompson** [comment]
I think this should be good for a (squash + ) merge - anything I'm forgetting?

**Comment by lilyminium** [comment]
No, looks good! I'd normally want to update CHANGELOG but I've let that fall somewhat behind so I could do that separately on a different PR.

**Comment by mattwthompson** [comment]
Great, thanks, I'll let you wrestle the beast at release time 👍

**Pull request merged**
